### ISSUE TITLE
 *** Assertion failure in -[NSUserDefaults setSecretObject:forKey:]

### ISSUE THREAD

**Issue by ichu501** [nielsmouthaan/SecureNSUserDefaults#3]
I have running in Xcode 6.3 and ios 8.3 .I tried to save the normal string in secure way i got below error:

2015-06-08 15:32:06.296 FedBook[2019:764561] *** Assertion failure in -[NSUserDefaults setSecretObject:forKey:], /Users/irshadpc/Desktop/iOS/check/Third Party Libraries/NSUserDefaults+SecureAdditions.m:190
2015-06-08 15:32:06.300 FedBook[2019:764561] Secret may not be nil when storing an object securely

**Comment by nielsmouthaan** [comment]
You first need to set a secret:

[[NSUserDefaults standardUserDefaults] setSecret:@"your_secret_goes_here"]

**Comment by ichu501** [comment]
Thanks :)  nielsmouthaan

**Comment by anshulpatel** [comment]
Hi Niel,
I'm trying to retrieve object for key using the below code but it is crashing. 
NSData *data = [[NSUserDefaults standardUserDefaults] secretObjectForKey:kLoginUserData];

Please help me out what i'm doing wrong ???

**Comment by nielsmouthaan** [comment]
You first need to set a secret:

[[NSUserDefaults standardUserDefaults] setSecret:@"your_secret_goes_here"]

Otherwise encryption/decryption will fail.

**Comment by anshulpatel** [comment]
Thanks for the reply. I had added that but code but in login where i'm doing the user data saving work. But now i have added that code in app delegate. So my problem got solved.
