### ISSUE TITLE
Update CocoaSecurity Version to remove warnings

### ISSUE THREAD

**Issue by brnunes** [nielsmouthaan/SecureNSUserDefaults#7]
The currently used version of CocoaSecurity (1.2.1) has a couple of warnings because it uses deprecated methods. Updating to the latest version (1.2.4) fixes them.

![image](https://cloud.githubusercontent.com/assets/1976718/13796927/e6b10772-eac6-11e5-868f-5b0b6784c874.png)

**Comment by abdulla-allaith-7** [comment]
CocoaSecurity (1.2.4) still shows the same warnings. I checked the repo and that's their latest version 😬         
Any advice on how to get rid of the warnings?
